stages:
  - test

test_10:
  image: node:10
  stage: test
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm install
    - npm run cover
  tags:
    - docker

test_8:
  image: node:8
  stage: test
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm install
    - npm run cover
  tags:
    - docker
