stages:
  - test
  - cover
  - release

test:node:10:
  image: node:10
  stage: test
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm install
    - npm test
  tags:
    - docker
  artifacts:
    paths:
      - coverage

test:node:9:
  image: node:9
  stage: test
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm install
    - npm test
  tags:
    - docker

test:node:8:
  image: node:8
  stage: test
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm install
    - npm test
  tags:
    - docker

coveralls:
  image: node:10
  dependencies:
    - test:node:10
    - test:node:9
    - test:node:8
  stage: cover
  only:
    - dev
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - npm install
    - npm run coveralls
  tags:
    - docker
  artifacts:
    paths:
      - coverage

release:
  image: node:10
  dependencies:
    - coveralls
  stage: release
  only:
    - dev
  cache:
    key: node_modules
    policy: pull
    paths:
      - node_modules
  script:
    - git checkout master
    - git merge dev --no-edit
    - git remote add upstream "$UPSTREAM"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "Robot Justin"
    - npm install
    - npm run bump
  tags:
    - docker
